# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer_like',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answer_like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question_like',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question_like',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(default='bob', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='questions.Tag'),
        ),
        migrations.DeleteModel(
            name='Answer_like',
        ),
        migrations.DeleteModel(
            name='Question_like',
        ),
        migrations.AddField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Profile'),
        ),
        migrations.AddField(
            model_name='answerlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Profile'),
        ),
    ]
