# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
