# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170420_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer_like',
            new_name='AnswerLike',
        ),
        migrations.RenameModel(
            old_name='Question_like',
            new_name='QuestionLike',
        ),
    ]
