# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20170418_1312'),
        ('questions', '0004_auto_20170417_2257'),
    ]

    operations = [
    ]
